services:
  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PASSWORD_DB}
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    env_file: .env
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
  website:
    build: .
    restart: always
    depends_on:
      - 'postgres'
    expose:
      - '3000'
    volumes:
      - '/opt/agroecologymap:/app/storage'
      - '/opt/dockers/logs:/app/log'
    env_file: .env
    healthcheck:
      test: ['CMD-SHELL', 'wget -q --spider --proxy=off localhost:3000/health || exit 1']
volumes:
  postgres:
