---
version: '2'

services:
  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PASSWORD_DB}
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    env_file: .env
  website:
    build: .
    restart: always
    depends_on:
      - 'postgres'
    expose:
      - '3000'
    volumes:
      - '/opt/agroecologymap:/app/public/system'
      - '/opt/dockers/logs:/app/log'
    env_file: .env

volumes:
  postgres:
